"""Initial migration

Revision ID: 0001
Revises:
Create Date: 2025-03-25 16:46:45.190131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tikee_pictures",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tikee_uuid", sa.String(), nullable=False),
        sa.Column("sequence", sa.String(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("resolution", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("shooting_date", sa.String(), nullable=False),
        sa.Column("metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_key"),
    )
    op.create_index(
        op.f("ix_tikee_pictures_sequence"), "tikee_pictures", ["sequence"], unique=False
    )
    op.create_index(
        op.f("ix_tikee_pictures_tikee_uuid"),
        "tikee_pictures",
        ["tikee_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tikee_pictures_tikee_uuid"), table_name="tikee_pictures")
    op.drop_index(op.f("ix_tikee_pictures_sequence"), table_name="tikee_pictures")
    op.drop_table("tikee_pictures")
    # ### end Alembic commands ###
